version: 2

jobs:
  cargoTests:
    docker:
      - image: rustlang/rust:nightly-slim
    steps:
      - checkout
      - run:
          command: |
            apt update && apt install -y libssl-dev pkg-config
            cargo test

  buildImage:
    docker:
      - image: web3f/ci-commons:v2.4.8
    resource_class: xlarge   
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            /scripts/build-image.sh web3f/uptime-probe .
  helmLint:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/uptime-probe

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/uptime-probe

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - cargoTests:
          filters:
            tags:
              only: /.*/
      - buildImage:
          context: dockerhub-bot
          filters:
            tags:
              only: /.*/
      - helmLint:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - cargoTests
            - buildImage
            - helmLint
      - publishImage:
          context: dockerhub-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - cargoTests
            - buildImage
            - integrationTests
      - publishChart:
          context: github-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - cargoTests
            - buildImage
            - integrationTests
