environment: production
origin:

image:
  repo: web3f/uptime-probe
  # tag: latest

config:
  port: 8080
  period: 300
  allow_redirections: false
  prometheus_rule_scope: "standard"
  sites:
  - url: "https://your.url"

prometheusRules:
  criticalEnabled: false

resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "300m"
    memory: "600Mi"
